/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetor.view;

import javax.swing.JOptionPane;
import sipetor.controller.ControllerLogin;
import sipetor.models.Login;
import sipetor.reports.GenerateReport;

/**
 *
 * @author Rizki Ramadhan
 */
public class FormMainMenu extends javax.swing.JFrame {
    private final ControllerLogin controllerLogin = new ControllerLogin();

    /**
     * Creates new form FormMainMenu
     */
    public FormMainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public FormMainMenu(String tampilUsername){
        initComponents();
        this.setLocationRelativeTo(null);
        lblUser.setText(tampilUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblUsername = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnQuit = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        mnAdmin = new javax.swing.JMenu();
        mnGolongan = new javax.swing.JMenuItem();
        mnKaryawan = new javax.swing.JMenuItem();
        mnAkun = new javax.swing.JMenuItem();
        mnMaster = new javax.swing.JMenu();
        mnSparepart = new javax.swing.JMenuItem();
        mnPelanggan = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        mnServiceMotor = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnTrans = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipetor Main Menu");

        jToolBar1.setRollover(true);

        lblUsername.setText("Username : ");
        jToolBar1.add(lblUsername);

        lblUser.setText("Guest");
        jToolBar1.add(lblUser);

        mnFile.setText("File");

        mnQuit.setText("Quit");
        mnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuitActionPerformed(evt);
            }
        });
        mnFile.add(mnQuit);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnFile.add(mnLogout);

        jMenuBar1.add(mnFile);

        mnAdmin.setText("Admin Data");

        mnGolongan.setText("Golongan");
        mnGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGolonganActionPerformed(evt);
            }
        });
        mnAdmin.add(mnGolongan);

        mnKaryawan.setText("Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        mnAdmin.add(mnKaryawan);

        mnAkun.setText("Akun");
        mnAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAkunActionPerformed(evt);
            }
        });
        mnAdmin.add(mnAkun);

        jMenuBar1.add(mnAdmin);

        mnMaster.setText("Master Data");

        mnSparepart.setText("Sparepart");
        mnSparepart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSparepartActionPerformed(evt);
            }
        });
        mnMaster.add(mnSparepart);

        mnPelanggan.setText("Pelanggan");
        mnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPelangganActionPerformed(evt);
            }
        });
        mnMaster.add(mnPelanggan);

        jMenuBar1.add(mnMaster);

        mnTransaksi.setText("Transaksi");

        mnServiceMotor.setText("Service Motor");
        mnServiceMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServiceMotorActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnServiceMotor);

        jMenuBar1.add(mnTransaksi);

        jMenu1.setText("Report");

        mnTrans.setText("Detail Transaksi");
        mnTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransActionPerformed(evt);
            }
        });
        jMenu1.add(mnTrans);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 257, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGolonganActionPerformed
        new FormMasterGolongan(this, true).setVisible(true);
    }//GEN-LAST:event_mnGolonganActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
        new FormMasterKaryawan(this, true).setVisible(true);
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuitActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah anda ingin Quit?");
        if(jawab == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnQuitActionPerformed

    private void mnAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAkunActionPerformed
        new FormAkunKaryawan(this, true).setVisible(true);
    }//GEN-LAST:event_mnAkunActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        this.dispose();
        new FormLogin(null, true).setVisible(true);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSparepartActionPerformed
        new FormMasterSparepart(this, true).setVisible(true);
    }//GEN-LAST:event_mnSparepartActionPerformed

    private void mnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPelangganActionPerformed
        new FormMasterPelanggan(this, true).setVisible(true);
    }//GEN-LAST:event_mnPelangganActionPerformed

    private void mnServiceMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServiceMotorActionPerformed
        new FormTransaksi().setVisible(true);
    }//GEN-LAST:event_mnServiceMotorActionPerformed

    private void mnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransActionPerformed
        GenerateReport report = new GenerateReport();
        report.GenerateReportTransaksi();
    }//GEN-LAST:event_mnTransActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu mnAdmin;
    private javax.swing.JMenuItem mnAkun;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnGolongan;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenuItem mnPelanggan;
    private javax.swing.JMenuItem mnQuit;
    private javax.swing.JMenuItem mnServiceMotor;
    private javax.swing.JMenuItem mnSparepart;
    private javax.swing.JMenuItem mnTrans;
    private javax.swing.JMenu mnTransaksi;
    // End of variables declaration//GEN-END:variables

    private void FormMasterGolongan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
