package sipetor.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sipetor.controller.ControllerSparepart;
import sipetor.models.Sparepart;

/**
 *
 * @author Rizki Ramadhan
 */

public class FormMasterSparepart extends javax.swing.JDialog {
    private final ControllerSparepart controllerSparepart = new ControllerSparepart();

    /**
     * Creates new form FormMasterSparepart
     */
    public FormMasterSparepart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTableSparepart(controllerSparepart.getAllData());
        txtIdSparepart.setText(controllerSparepart.generateID()+"");
        this.setLocationRelativeTo(null);
    }
    
    private void setTableSparepart(List<Sparepart> listSparepart) {
        if(listSparepart==null){
            JOptionPane.showMessageDialog(this, "Data " 
                  + "Golongan gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
                new String[] {
                    "Id Sparepart",
                    "Nama Sparepart",
                    "Harga Sparepart",
                    "Stock Sparepart"
                }
            );
            
            for (Sparepart s : listSparepart) {
                Object [] o = new Object[4];
                o[0] = s.getId_sparepart();
                o[1] = s.getNama_sparepart();
                o[2] = s.getHarga_sparepart();
                o[3] = s.getStock_sparepart();
                tableModel.addRow(o);
            }
            tblSparepart.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tblSparepart.setModel(tableModel);
        }
    }
    
    private void setClear(){
        txtIdSparepart.setText(controllerSparepart.generateID()+"");
        txtNamaSparepart.setText("");
        txtHargaSparepart.setText("");
        txtStockSparepart.setText("");
        btnSimpan.setText("Simpan");
        setTableSparepart(controllerSparepart.getAllData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupSparepart = new javax.swing.JPopupMenu();
        mnDelete = new javax.swing.JMenuItem();
        lblSparepart = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblIdSparepart = new javax.swing.JLabel();
        lblNamaSparepart = new javax.swing.JLabel();
        txtNamaSparepart = new javax.swing.JTextField();
        lblHargaSparepart = new javax.swing.JLabel();
        txtHargaSparepart = new javax.swing.JTextField();
        lblStockSparepart = new javax.swing.JLabel();
        txtStockSparepart = new javax.swing.JTextField();
        txtIdSparepart = new javax.swing.JTextField();
        lblAksi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        outCommand = new javax.swing.JLabel();
        lblOutput = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSparepart = new javax.swing.JTable();

        mnDelete.setText("Delete");
        mnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeleteActionPerformed(evt);
            }
        });
        popupSparepart.add(mnDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sipetor Sparepart");

        lblSparepart.setText("Field Sparepart");

        lblIdSparepart.setText("ID Sparepart : ");

        lblNamaSparepart.setText("Nama Sparepart : ");

        lblHargaSparepart.setText("Harga Sparepart : ");

        lblStockSparepart.setText("Stock Sparepart : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaSparepart)
                            .addComponent(lblIdSparepart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaSparepart)
                            .addComponent(txtIdSparepart)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHargaSparepart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHargaSparepart))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblStockSparepart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStockSparepart)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSparepart)
                    .addComponent(txtIdSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSparepart)
                    .addComponent(txtNamaSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHargaSparepart)
                    .addComponent(txtHargaSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockSparepart)
                    .addComponent(txtStockSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAksi.setText("Aksi");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        outCommand.setText("Ready");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(outCommand)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addGap(18, 18, 18)
                .addComponent(outCommand)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblOutput.setText("Output");

        tblSparepart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Sparepart", "Nama Sparepart", "Harga Sparepart", "Stock Sparepart"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSparepart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSparepartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSparepartMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSparepart);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSparepart)
                            .addComponent(lblAksi)
                            .addComponent(lblOutput))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblSparepart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int id_sparepart = Integer.parseInt(txtIdSparepart.getText());
        String nama_sparepart = txtNamaSparepart.getText();
        int harga_sparepart = Integer.parseInt(txtHargaSparepart.getText());
        int stock_sparepart = Integer.parseInt(txtStockSparepart.getText());
        
        Sparepart data = new Sparepart(
                id_sparepart,
                nama_sparepart,
                harga_sparepart,
                stock_sparepart
        );
        
        if(btnSimpan.getText().equals("Simpan")){
            if(controllerSparepart.insertSparepart(data)){
                outCommand.setText("Insert Berhasil");
            }
            else{
                outCommand.setText("Insert Gagal");
            }
        }
        else{
            if(controllerSparepart.updateSparepart(data)){
                outCommand.setText("Update Berhasil");
            }
            else{
                outCommand.setText("Update Gagal");
            }
        }
        setClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setClear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void mnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane,
                "Apakah Yakin untuk Didelete?",
                "Delete Dialog", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            int id = Integer.parseInt(tblSparepart.getModel().getValueAt(tblSparepart.getSelectedRow(), 0).toString());
            controllerSparepart.deleteSparepart(id);
            setClear();
        }
    }//GEN-LAST:event_mnDeleteActionPerformed

    private void tblSparepartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSparepartMousePressed
        if(evt.getClickCount()==2){
            int idxrow = tblSparepart.getSelectedRow();
            txtIdSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 0).toString());
            txtNamaSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 1).toString());
            txtHargaSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 2).toString());
            txtStockSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 3).toString());
            btnSimpan.setText("Update");
        }
        if(evt.isPopupTrigger()){
            popupSparepart.show(tblSparepart, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblSparepartMousePressed

    private void tblSparepartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSparepartMouseReleased
        if(evt.getClickCount()==2){
            int idxrow = tblSparepart.getSelectedRow();
            txtIdSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 0).toString());
            txtNamaSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 1).toString());
            txtHargaSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 2).toString());
            txtStockSparepart.setText(tblSparepart.getModel().getValueAt(idxrow, 3).toString());
            btnSimpan.setText("Update");
        }
        if(evt.isPopupTrigger()){
            popupSparepart.show(tblSparepart, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblSparepartMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasterSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasterSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasterSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasterSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMasterSparepart dialog = new FormMasterSparepart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAksi;
    private javax.swing.JLabel lblHargaSparepart;
    private javax.swing.JLabel lblIdSparepart;
    private javax.swing.JLabel lblNamaSparepart;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblSparepart;
    private javax.swing.JLabel lblStockSparepart;
    private javax.swing.JMenuItem mnDelete;
    private javax.swing.JLabel outCommand;
    private javax.swing.JPopupMenu popupSparepart;
    private javax.swing.JTable tblSparepart;
    private javax.swing.JTextField txtHargaSparepart;
    private javax.swing.JTextField txtIdSparepart;
    private javax.swing.JTextField txtNamaSparepart;
    private javax.swing.JTextField txtStockSparepart;
    // End of variables declaration//GEN-END:variables
}
