/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetor.view;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sipetor.controller.ControllerDetailTransaksi;
import sipetor.controller.ControllerHeadTransaksi;
import sipetor.controller.ControllerKaryawan;
import sipetor.controller.ControllerPelanggan;
import sipetor.controller.ControllerSparepart;
import sipetor.models.DetailTransaksi;
import sipetor.models.HeadTransaksi;
import sipetor.models.Karyawan;
import sipetor.models.Pelanggan;
import sipetor.models.Sparepart;

/**
 *
 * @author Rizki Ramadhan
 */
public class FormTransaksi extends javax.swing.JFrame {
    ControllerKaryawan controllerKaryawan = new ControllerKaryawan();
    ControllerPelanggan controllerPelanggan = new ControllerPelanggan();
    ControllerSparepart controllerSparepart = new ControllerSparepart();
    ControllerDetailTransaksi controllerDetailTransaksi = new ControllerDetailTransaksi();
    ControllerHeadTransaksi controllerHeadTransaksi = new ControllerHeadTransaksi();
    List<DetailTransaksi> collection = new ArrayList<>();
    int totalPembelian = 0;
    float ppn = 0;
    float grandTotal = 0;
    
    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchData = new javax.swing.JDialog();
        lblNama = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblHasil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        lblHeadTransaksi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTgl = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblIDTransaksi = new javax.swing.JLabel();
        lblTnkb = new javax.swing.JLabel();
        lblTNKB = new javax.swing.JLabel();
        lblMontir = new javax.swing.JLabel();
        lblIDKaryawan = new javax.swing.JLabel();
        lblNamaPelanggan = new javax.swing.JLabel();
        lblNamaMontir = new javax.swing.JLabel();
        btnPelanggan = new javax.swing.JButton();
        btnMontir = new javax.swing.JButton();
        lblDetailTransaksi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        btnTambahDetail = new javax.swing.JButton();
        btnDeleteDetail = new javax.swing.JButton();
        btnDetailPembayaran = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbltotal = new javax.swing.JLabel();
        lblTotalPembelian = new javax.swing.JLabel();
        lblppn = new javax.swing.JLabel();
        lblPPN = new javax.swing.JLabel();
        lblgrand = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lbljumlah = new javax.swing.JLabel();
        txtPembayaran = new javax.swing.JTextField();
        lblkembali = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        lblNama.setText("Nama : ");

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPencarianKeyTyped(evt);
            }
        });

        btnCari.setText("Cari");

        lblHasil.setText("Hasil Pencarian");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblResult);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblHasil))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout searchDataLayout = new javax.swing.GroupLayout(searchData.getContentPane());
        searchData.getContentPane().setLayout(searchDataLayout);
        searchDataLayout.setHorizontalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchDataLayout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchDataLayout.setVerticalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeadTransaksi.setText("Head Transaksi");

        lblTgl.setText("Tanggal : ");

        lblTanggal.setText("tanggal");

        lblID.setText("ID Transaksi : ");

        lblIDTransaksi.setText("id_transaksi");

        lblTnkb.setText("TNKB : ");

        lblTNKB.setText("tnkb");

        lblMontir.setText("Montir : ");

        lblIDKaryawan.setText("id_karyawan");

        lblNamaPelanggan.setText("nama_pemilik");

        lblNamaMontir.setText("nama_montir");

        btnPelanggan.setText("Search Pelanggan");
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnMontir.setText("Search Montir");
        btnMontir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTgl)
                        .addGap(28, 28, 28)
                        .addComponent(lblTanggal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(lblTnkb)
                            .addComponent(lblMontir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDTransaksi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTNKB)
                                    .addComponent(lblIDKaryawan))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaPelanggan)
                                    .addComponent(lblNamaMontir))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMontir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPelanggan))))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTgl)
                    .addComponent(lblTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(lblIDTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTnkb)
                    .addComponent(lblTNKB)
                    .addComponent(lblNamaPelanggan)
                    .addComponent(btnPelanggan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontir)
                    .addComponent(lblIDKaryawan)
                    .addComponent(lblNamaMontir)
                    .addComponent(btnMontir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblDetailTransaksi.setText("Detail Transaksi");

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Registrasi", "ID Transaksi", "ID Sparepart", "Jumlah Beli", "Total Beli"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetail);

        btnTambahDetail.setText("+");
        btnTambahDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDetailActionPerformed(evt);
            }
        });

        btnDeleteDetail.setText("-");
        btnDeleteDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambahDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteDetail)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahDetail)
                    .addComponent(btnDeleteDetail))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnDetailPembayaran.setText("Detail Pembayaran");

        lbltotal.setText("Total Pembelian : ");

        lblTotalPembelian.setText("0");

        lblppn.setText("PPN 10% : ");

        lblPPN.setText("0");

        lblgrand.setText("Grand Total : ");

        lblGrandTotal.setText("0");

        lbljumlah.setText("Jumlah Bayar : ");

        txtPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPembayaranKeyTyped(evt);
            }
        });

        lblkembali.setText("Kembali : ");

        lblKembalian.setText("0");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(lblppn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPPN))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(lbltotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTotalPembelian)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgrand)
                            .addComponent(lbljumlah))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblGrandTotal))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKembalian)
                                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblkembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotal)
                    .addComponent(lblTotalPembelian)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblppn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnClear)
                        .addComponent(lblPPN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(lblgrand)
                    .addComponent(lblGrandTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljumlah)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkembali)
                    .addComponent(lblKembalian))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeadTransaksi)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDetailTransaksi)
                            .addComponent(btnDetailPembayaran))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeadTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDetailTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetailPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        setTablePelanggan(controllerPelanggan.getAllData());
        searchData.requestFocusInWindow();
        searchData.setVisible(true);
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnMontirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontirActionPerformed
        setTableKaryawan(controllerKaryawan.getAllData());
        searchData.setVisible(true);
    }//GEN-LAST:event_btnMontirActionPerformed

    private void btnTambahDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDetailActionPerformed
        setTableSparepart(controllerSparepart.getAllData());
        searchData.setVisible(true);
    }//GEN-LAST:event_btnTambahDetailActionPerformed

    private void btnDeleteDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDetailActionPerformed
        if(collection.size() >= 0){
            totalPembelian -= collection.get(0).getTotal_beli();
            lblTotalPembelian.setText(totalPembelian+"");
            ppn = totalPembelian * 0.1f;
            grandTotal = totalPembelian + ppn;
            lblPPN.setText(ppn + "");
            lblGrandTotal.setText(grandTotal + "");
            collection.remove(0);
            setTableDetail(collection);
        }
    }//GEN-LAST:event_btnDeleteDetailActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        HeadTransaksi head = new HeadTransaksi(
                lblIDTransaksi.getText(), lblIDKaryawan.getText(), 
                lblTNKB.getText(), lblTanggal.getText(), 
                Integer.parseInt(txtPembayaran.getText()),
                Integer.parseInt(lblTotalPembelian.getText())
        );
        controllerHeadTransaksi.insertHeadTransaksi(head);
        
        for(DetailTransaksi data : collection){
            DetailTransaksi detail = new DetailTransaksi(
                    controllerDetailTransaksi.generateID(),data.getId_transaksi(),
                    data.getId_sparepart(),data.getJumlah_beli(),
                    data.getTotal_beli()
            );
            controllerDetailTransaksi.insertDetailTransaksi(detail);
        }
        setClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setClear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtPembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPembayaranKeyTyped
        if(evt.getKeyCode() == 0){
           if(!txtPembayaran.getText().equals("")){
                int money = Integer.parseInt(txtPembayaran.getText());
                float change = money - grandTotal;
                lblKembalian.setText((change < 0 ? 0+"" : change+""));
            }
        }
    }//GEN-LAST:event_txtPembayaranKeyTyped

    private void txtPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyTyped
        String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
        if(colName.equals("NIK")){
            setTableKaryawan(controllerKaryawan.getAllKaryawanByName(txtPencarian.getText()));
        } else if(colName.equals("Id Pelanggan")){
            setTablePelanggan(controllerPelanggan.getAllPelangganByName(txtPencarian.getText()));
        } else{
            setTableSparepart(controllerSparepart.getAllSparepartByName(txtPencarian.getText()));
        }
    }//GEN-LAST:event_txtPencarianKeyTyped

    private void tblResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMousePressed
        if(evt.getClickCount() == 2){
            String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
            int idxrow = tblResult.getSelectedRow();
            if(colName.equals("NIK")){
                lblIDKaryawan.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
                lblNamaMontir.setText(tblResult.getModel().getValueAt(idxrow, 2).toString());
            } else if(colName.equals("Id Pelanggan")){
                lblTNKB.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
                lblNamaPelanggan.setText(tblResult.getModel().getValueAt(idxrow, 1).toString());
            } else{
                int id_reg = 0;
                String id_transaksi = lblIDTransaksi.getText();
                String id_sparepart = tblResult.getModel().getValueAt(idxrow, 0).toString();
                int jumlah_beli = 1;
                int stotal_beli = Integer.parseInt(tblResult.getModel().getValueAt(idxrow,2).toString());
                int total_beli = jumlah_beli * stotal_beli;
                
                DetailTransaksi data = new DetailTransaksi(id_reg, id_transaksi, 
                        id_sparepart, jumlah_beli, 
                        total_beli);
                totalPembelian += total_beli;
                lblTotalPembelian.setText(totalPembelian+"");
                ppn = totalPembelian * 0.1f;
                grandTotal = totalPembelian + ppn;
                lblPPN.setText(ppn + "");
                lblGrandTotal.setText(grandTotal + "");
                collection.add(data);
            }
            searchData.dispose();
            setTableDetail(collection);
        }
    }//GEN-LAST:event_tblResultMousePressed

    public void initData() {
        Calendar c = Calendar.getInstance();
        String date = c.get(Calendar.YEAR) +"/"+ (c.get(Calendar.MONTH)+1) +"/"+ c.get(Calendar.DATE);
        lblTanggal.setText(date);
        lblIDTransaksi.setText(controllerHeadTransaksi.generateID()+"");
        setTableDetail(collection);
    }
    
    private void setTablePelanggan(List<Pelanggan> listPelanggan){
       if(listPelanggan==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }
       else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
                   new String[] {
                       "Id Pelanggan",
                       "Nama Pelanggan",
                       "Alamat Pelanggan"
                   }
           );
           
           for (Pelanggan p : listPelanggan) {
               Object[] o = new Object[3];
               o[0] = p.getTnkb_pelanggan();
               o[1] = p.getNama_pelanggan();
               o[2] = p.getAlamat_pelanggan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableKaryawan(List<Karyawan> listKaryawan){
        if(listKaryawan==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }
       else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
                   new String[] {
                       "NIK",
                       "Id Golongan",
                       "Nama Karyawan",
                       "Alamat Karyawan",
                       "Email Karyawan"
                   }
           );
           
           for (Karyawan k : listKaryawan) {
               Object[] o = new Object[5];
               o[0] = k.getNik();
               o[1] = k.getId_golongan();
               o[2] = k.getNama_karyawan();
               o[3] = k.getAlamat_karyawan();
               o[4] = k.getEmail_karyawan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableSparepart(List<Sparepart> listSparepart){
        if(listSparepart==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }
       else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
                   new String[] {
                       "Id Sparepart",
                       "Nama Sparepart",
                       "Harga Sparepart",
                       "Stock Sparepart"
                   }
           );
           
           for (Sparepart s : listSparepart) {
               Object[] o = new Object[4];
               o[0] = s.getId_sparepart();
               o[1] = s.getNama_sparepart();
               o[2] = s.getHarga_sparepart();
               o[3] = s.getStock_sparepart();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableDetail(List<DetailTransaksi> listDetailTransaksi){
        if(listDetailTransaksi==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }
       else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
                   new String[] {
                       "Id Registrasi",
                       "Id Transaksi",
                       "Id Sparepart",
                       "Jumlah Beli",
                       "Total Beli"
                   }
           );
           
           for (DetailTransaksi dt : listDetailTransaksi) {
               Object[] o = new Object[5];
               o[0] = dt.getId_reg();
               o[1] = dt.getId_transaksi();
               o[2] = dt.getId_sparepart();
               o[3] = dt.getJumlah_beli();
               o[4] = dt.getTotal_beli();
               tableModel.addRow(o);
           }
           tblDetail.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblDetail.setModel(tableModel);
       }
    }
    
    private void setClear(){
        //membersihkan data head transaksi
        Calendar c = Calendar.getInstance();
        String date = c.get(Calendar.YEAR) +"/"+ (c.get(Calendar.MONTH)+1) +"/"+ c.get(Calendar.DATE);
        lblTanggal.setText(date);
        lblIDTransaksi.setText(controllerHeadTransaksi.generateID()+"");
        lblIDKaryawan.setText("id_karyawan");
        lblNamaMontir.setText("id_montir");
        lblTNKB.setText("tnkb");
        lblNamaPelanggan.setText("nama_pelanggan");
        
        //membersihkan data detail transaksi
        collection.clear();
        setTableDetail(collection);
        
        //membersihkan data detail perhitungan
        lblTotalPembelian.setText("0");
        lblPPN.setText("0");
        lblGrandTotal.setText("0");
        txtPembayaran.setText("0");
        lblKembalian.setText("0");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteDetail;
    private javax.swing.JLabel btnDetailPembayaran;
    private javax.swing.JButton btnMontir;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahDetail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDetailTransaksi;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblHeadTransaksi;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDKaryawan;
    private javax.swing.JLabel lblIDTransaksi;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblMontir;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaMontir;
    private javax.swing.JLabel lblNamaPelanggan;
    private javax.swing.JLabel lblPPN;
    private javax.swing.JLabel lblTNKB;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JLabel lblTnkb;
    private javax.swing.JLabel lblTotalPembelian;
    private javax.swing.JLabel lblgrand;
    private javax.swing.JLabel lbljumlah;
    private javax.swing.JLabel lblkembali;
    private javax.swing.JLabel lblppn;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JDialog searchData;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
