/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipetor.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sipetor.controller.ControllerGolongan;
import sipetor.controller.ControllerKaryawan;
import sipetor.models.Golongan;
import sipetor.models.Karyawan;

/**
 *
 * @author Rizki Ramadhan
 */
public class FormMasterKaryawan extends javax.swing.JDialog {
    private final ControllerKaryawan controllerKaryawan = new ControllerKaryawan();
    private final ControllerGolongan controllerGolongan = new ControllerGolongan();
    /**
     * Creates new form FormMasterKaryawan
     */
    public FormMasterKaryawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTableKaryawan(controllerKaryawan.getAllData());
        setComboKaryawan(controllerGolongan.getAllData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        popupKaryawan = new javax.swing.JPopupMenu();
        mnDelete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblIdKaryawan = new javax.swing.JLabel();
        txtIdKaryawan = new javax.swing.JTextField();
        lblKaryawan = new javax.swing.JLabel();
        cbxKaryawan = new javax.swing.JComboBox();
        lblNamaKaryawan = new javax.swing.JLabel();
        txtNamaKaryawan = new javax.swing.JTextField();
        lblAlamatKaryawan = new javax.swing.JLabel();
        txtAlamatKaryawan = new javax.swing.JTextField();
        lblEmailKaryawan = new javax.swing.JLabel();
        txtEmailKaryawan = new javax.swing.JTextField();
        lblField = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        outCommand = new javax.swing.JLabel();
        lblAksi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblOutput = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mnDelete.setText("Delete");
        mnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeleteActionPerformed(evt);
            }
        });
        popupKaryawan.add(mnDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sipetor Karyawan");

        lblIdKaryawan.setText("NIK");

        lblKaryawan.setText("Golongan Karyawan");

        cbxKaryawan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-Administrator", "2-Karyawan" }));

        lblNamaKaryawan.setText("Nama Karyawan");

        lblAlamatKaryawan.setText("Alamat Karyawan");

        lblEmailKaryawan.setText("Email Karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKaryawan)
                    .addComponent(lblIdKaryawan)
                    .addComponent(lblNamaKaryawan)
                    .addComponent(lblAlamatKaryawan)
                    .addComponent(lblEmailKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailKaryawan)
                    .addComponent(txtAlamatKaryawan)
                    .addComponent(txtNamaKaryawan)
                    .addComponent(txtIdKaryawan)
                    .addComponent(cbxKaryawan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdKaryawan)
                    .addComponent(txtIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKaryawan)
                    .addComponent(cbxKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamatKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamatKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailKaryawan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblField.setText("Field Karyawan");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        outCommand.setText("Ready");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outCommand)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addGap(18, 18, 18)
                .addComponent(outCommand)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblAksi.setText("Aksi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        lblOutput.setText("Output");

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIK", "Golongan", "Nama Karyawan", "Alamat Karyawan", "Email Karyawan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKaryawanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblKaryawan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblField)
                            .addComponent(lblAksi)
                            .addComponent(lblOutput))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nik = txtIdKaryawan.getText();
        String nama_karyawan = txtNamaKaryawan.getText();
        String alamat_karyawan = txtAlamatKaryawan.getText();
        String email_karyawan = txtEmailKaryawan.getText();
        String cbx = cbxKaryawan.getSelectedItem().toString();
        
        //kode pengambilan kode golongan di combobox
        char[] id = new char[1];
        for(int x=0;x<cbx.length();x++){
            if(cbx.charAt(x) != '-'){
                id[x] = cbx.charAt(x);
            }else{
                break;
            }
        }
        //return kode sebagai byte
        byte id_golongan = Byte.parseByte(new String(id));
        
        Karyawan data = new Karyawan(
                nik,
                nama_karyawan,
                alamat_karyawan,
                email_karyawan,
                id_golongan
        );
        
        if(btnSimpan.getText().equals("Simpan")){
            if(controllerKaryawan.insertKaryawan(data)){
                outCommand.setText("Insert Berhasil");
            }else{
                outCommand.setText("Insert Gagal");
            }    
        } else{
            if(controllerKaryawan.updateKaryawan(data)){
                outCommand.setText("Update Berhasil");
            }else{
                outCommand.setText("Update Gagal");
            }  
        }
        setClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblKaryawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMousePressed
        if(evt.getClickCount()==2){
            int idxrow = tblKaryawan.getSelectedRow();
            txtIdKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 0).toString());
            txtNamaKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 2).toString());
            txtAlamatKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 3).toString());
            txtEmailKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 4).toString());
            btnSimpan.setText("Update");
        }
        if(evt.isPopupTrigger()){
            popupKaryawan.show(tblKaryawan, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblKaryawanMousePressed

    private void tblKaryawanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseReleased
        if(evt.getClickCount()==2){
            int idxrow = tblKaryawan.getSelectedRow();
            txtIdKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 0).toString());
            txtNamaKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 2).toString());
            txtAlamatKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 3).toString());
            txtEmailKaryawan.setText(tblKaryawan.getModel().getValueAt(idxrow, 4).toString());
            btnSimpan.setText("Update");
        }
        if(evt.isPopupTrigger()){
            popupKaryawan.show(tblKaryawan, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblKaryawanMouseReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setClear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void mnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane,
                "Apakah Yakin untuk Didelete?",
                "Delete Dialog", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            String nik = tblKaryawan.getModel().getValueAt(tblKaryawan.getSelectedRow(), 0).toString();
            controllerKaryawan.deleteKaryawan(nik);
            setClear();
        }
    }//GEN-LAST:event_mnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void setTableKaryawan(List<Karyawan> listKaryawan){
        if (listKaryawan==null){
            JOptionPane.showMessageDialog(this, "Data karyawan gagal diambil dari database",
                    "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
                new String[] {
                    "NIK",
                    "Golongan",
                    "Nama Karyawan",
                    "Alamat Karyawan",
                    "Email Karyawan"
                }
            );
            
            for (Karyawan k : listKaryawan) {
                Object[] o = new Object[5];
                o[0] = k.getNik();
                o[1] = k.getId_golongan();
                o[2] = k.getNama_karyawan();
                o[3] = k.getAlamat_karyawan();
                o[4] = k.getEmail_karyawan();
                tableModel.addRow(o);
            }
            tblKaryawan.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
            tblKaryawan.setModel(tableModel);
        }
    }
    
    private void setComboKaryawan(List<Golongan> listGolongan){
        if (listGolongan==null){
            JOptionPane.showMessageDialog(this, "Data karyawan gagal diambil dari database",
                    "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for(Golongan g : listGolongan){
                model.addElement(g.getId_golongan() + "-" +g.getNama_golongan());
            }
            cbxKaryawan.setModel(model);
        }
    }
    
    private void setClear(){
        txtIdKaryawan.setText("");
        txtNamaKaryawan.setText("");
        txtAlamatKaryawan.setText("");
        txtEmailKaryawan.setText("");
        cbxKaryawan.setSelectedIndex(0);
        btnSimpan.setText("Simpan");
        setTableKaryawan(controllerKaryawan.getAllData());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMasterKaryawan dialog = new FormMasterKaryawan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbxKaryawan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAksi;
    private javax.swing.JLabel lblAlamatKaryawan;
    private javax.swing.JLabel lblEmailKaryawan;
    private javax.swing.JLabel lblField;
    private javax.swing.JLabel lblIdKaryawan;
    private javax.swing.JLabel lblKaryawan;
    private javax.swing.JLabel lblNamaKaryawan;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JMenuItem mnDelete;
    private javax.swing.JLabel outCommand;
    private javax.swing.JPopupMenu popupKaryawan;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextField txtAlamatKaryawan;
    private javax.swing.JTextField txtEmailKaryawan;
    private javax.swing.JTextField txtIdKaryawan;
    private javax.swing.JTextField txtNamaKaryawan;
    // End of variables declaration//GEN-END:variables
}
